name: Build And Test
on:
  push:
    branches:
      - main
      - 'US_[0-9][0-9]'
  pull_request:
    branches:
      - main
      - 'US_[0-9][0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21.0.4
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21.0.4'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.10.1'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
     
    - name: Run Tests in Headless Mode
      run: |
        export _JAVA_OPTIONS="-Djava.awt.headless=true" 
      env:
        DISPLAY: :99  # Xvfb for headless UI tests

    - name: Setup headless display (if needed for UI tests like JavaFX or Swing)
      uses: GabrielBB/xvfb-action@v1.6
   
    - name: Build and Test
      run: ./gradlew build test
