name: Auto-format with Spotless

on:
  push:
    branches:
      - main
      - 'US_[0-9][0-9]'
  pull_request:
    branches:
      - main
      - 'US_[0-9][0-9]'

jobs:
  spotless-apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # Ensure full history for committing changes

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Run Spotless Apply to fix formatting
      run: ./gradlew spotlessApply

    - name: Check for changes
      run: git diff --exit-code || echo "Changes detected"

    - name: Commit changes if any
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Apply Spotless Google Java Format" || echo "No changes to commit"

    - name: Push changes back to repository
      run: git push origin HEAD:${{ github.ref }}
