name: Check Google Java Format with Spotless

on:
  push:
    branches:
      - main
      - 'US_[0-9][0-9]'
  pull_request:
    branches:
      - main
      - 'US_[0-9][0-9]'

jobs:
  spotless-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21.0.4
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.4'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Run Spotless Check for Google Java Format
      run: ./gradlew spotlessCheck

    - name: Fail the job if formatting is incorrect
      if: failure()
      run: exit 1
